name: e_commerce_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.8.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.2.1+1
  equatable: ^2.0.0
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_ui_firestore: ^1.5.15
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^6.0.3
  flutter_hooks: ^0.20.4
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  flutter_svg: ^2.0.9
  form_validator: ^2.1.1
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: ^13.0.1
  google_sign_in: ^6.1.4
  hooks_riverpod: ^2.4.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  modal_progress_hud_nsn: ^0.4.0
  riverpod_annotation: ^2.3.4
  riverpod_state: ^0.1.1
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.6.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9

flutter_assets:
  assets_path: assets/
  output_path: lib/core/utils/constants/
  filename: assets.dart

  # Optional
  integrations:
    flutter_svg: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/svg/
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
