name: e_commerce_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.0
  cloud_firestore: ^5.6.7
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.2.1+1
  equatable: ^2.0.0
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  firebase_ui_firestore: ^1.7.1
  firebase_storage: ^12.4.5
  firebase_app_check: ^0.3.2+5
  flutter_facebook_auth: ^6.0.3
  flutter_hooks: ^0.20.4
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  flutter_svg: ^2.0.9
  form_validator: ^2.1.1
  gap: ^3.0.1
  go_router: ^13.0.1
  google_sign_in: ^6.1.4
  hooks_riverpod: ^2.4.0
  intl: ^0.19.0
  riverpod_annotation: ^2.3.4
  riverpod_state: ^0.1.1
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  image_picker: ^1.0.7

  # models
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # lints
  custom_lint: ^0.7.5
  flutter_lints: ^2.0.0
  riverpod_lint: ^2.3.9

  # code gen
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  freezed: ^3.0.6

flutter_assets:
  assets_path: assets/
  output_path: lib/core/utils/constants/
  filename: assets.dart

  # Optional
  integrations:
    flutter_svg: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/svg/
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
