 import 'package:e_commerce_app/Features/home/data/models/rating_model.dart';
import 'package:e_commerce_app/Features/product/data/models/product_model.dart';

const products = [
     ProductModel(
      id: 1,
      title: 'Smartphone X',
      price: 799.99,
      description: 'Powerful smartphone with advanced features.',
      category: 'Electronics',
      image: 'smartphone_x.jpg',
      rating: Rating(rate: 4.7, count: 120),
    ),
    ProductModel(
      id: 2,
      title: 'Fitness Tracker Pro',
      price: 129.99,
      description: 'Track your fitness and health with this advanced tracker.',
      category: 'Fitness',
      image: 'fitness_tracker_pro.jpg',
      rating: Rating(rate: 4.2, count: 90),
    ),
    ProductModel(
      id: 3,
      title: 'Designer Handbag',
      price: 299.99,
      description: 'Elegant and stylish designer handbag for any occasion.',
      category: 'Fashion',
      image: 'designer_handbag.jpg',
      rating: Rating(rate: 4.5, count: 110),
    ),
    ProductModel(
      id: 4,
      title: '4K Smart TV',
      price: 899.99,
      description: 'Immerse yourself in stunning 4K resolution with this smart TV.',
      category: 'Electronics',
      image: '4k_smart_tv.jpg',
      rating: Rating(rate: 4.8, count: 150),
    ),
    ProductModel(
      id: 5,
      title: 'Coffee Maker Deluxe',
      price: 59.99,
      description: 'Brew delicious coffee with this high-end coffee maker.',
      category: 'Kitchen',
      image: 'coffee_maker_deluxe.jpg',
      rating: Rating(rate: 4.4, count: 80),
    ),
    ProductModel(
      id: 6,
      title: 'Gaming Laptop',
      price: 1499.99,
      description: 'Experience gaming at its best with this powerful laptop.',
      category: 'Electronics',
      image: 'gaming_laptop.jpg',
      rating: Rating(rate: 4.9, count: 180),
    ),
    ProductModel(
      id: 7,
      title: 'Running Shoes',
      price: 89.99,
      description: 'Comfortable and stylish running shoes for your active lifestyle.',
      category: 'Footwear',
      image: 'running_shoes.jpg',
      rating: Rating(rate: 4.6, count: 100),
    ),
    ProductModel(
      id: 8,
      title: 'Wireless Earbuds',
      price: 129.99,
      description: 'Enjoy high-quality audio with these wireless earbuds.',
      category: 'Electronics',
      image: 'wireless_earbuds.jpg',
      rating: Rating(rate: 4.3, count: 120),
    ),
    ProductModel(
      id: 9,
      title: 'Compact Camera',
      price: 499.99,
      description: 'Capture memories with this feature-packed compact camera.',
      category: 'Photography',
      image: 'compact_camera.jpg',
      rating: Rating(rate: 4.7, count: 90),
    ),
    ProductModel(
      id: 10,
      title: 'Home Gym Equipment',
      price: 799.99,
      description: 'Build your home gym with this versatile and durable equipment.',
      category: 'Fitness',
      image: 'home_gym_equipment.jpg',
      rating: Rating(rate: 4.5, count: 110),
    ),
  ];